import 'package:flutter/cupertino.dart';
import 'package:omnitics/Widgets/OtherAnswersCard.dart';
import 'package:omnitics/Widgets/SliderCard.dart';
import 'package:omnitics/Widgets/YesNoCard.dart';

class SurveyQuestions
{
  final List<Widget> questionList = [
    SliderCard(question: "How old are you?",min: 18, max: 100,index: 0, changeFont: true,),
    OtherAnswersCard(question: "Are you Male or Female?", numberOfAnswers: 2, answerOne: "Male", answerTwo: "Female",index: 1,),
    OtherAnswersCard(question: "What do you identify as?", numberOfAnswers: 4, answerOne: "White, non-hispanic", answerTwo: "Black, non-hispanic", answerThree: "White, Hispanic", answerFour: "Black, Hispanic",index: 2,),
    OtherAnswersCard(question: "How many years have you been in school?",numberOfAnswers: 3, answerOne: "Less than 8 years", answerTwo: "8 - 11 years", answerThree: "12 years or more",index: 3,),
    OtherAnswersCard(question: "What is your marriage status?", numberOfAnswers: 4, answerOne: "Married", answerTwo: "Living as Married", answerThree: "Widowed", answerFour: "Unmarried",index: 4,),
    OtherAnswersCard(question: "What kind of work do you do?", numberOfAnswers: 4, answerOne: "Homemaker", answerTwo: "Working", answerThree: "Unemployed", answerFour: "Student",index: 5,),
    OtherAnswersCard(question: "What is your Body Mass Index(BMI)?",numberOfAnswers: 4, answerOne:"0 - 18.5",answerTwo: "18.5 - 25",answerThree:"25 - 30" ,answerFour:"30+",index: 6,),
    SliderCard(question: "What was your weight at 20 years?(Lbs)",min: 50.0 ,max: 300.0, index: 7,changeFont: true,),
    YesNoCard(question: "Did you ever have arthritis?",index: 8,),
    YesNoCard(question: "Did you ever have chronic bronchitis?",index: 9),
    YesNoCard(question: "Did you ever have a colon related co-morbidity(ulceraive colitis, Crohn's disease, Gardner's syndrome, famililial polyposis)?",index: 10),
    YesNoCard(question: "Did you ever have diabetes?",index: 11),
    YesNoCard(question: "Did you ever have diverticulitis or diverticulosis?",index: 12),
    YesNoCard(question: "Did you ever have emphysema?",index: 13),
    YesNoCard(question: "Did you ever have gall bladder stones or inflammation?",index: 14),
    YesNoCard(question: "Did you ever have coronary heart disease or heart attack?",index: 15),
    YesNoCard(question: "Did you ever have high blood pressure?",index: 16),
    YesNoCard(question: "Did you ever have a liver related comorbidity(hepatitis or cirrhosis)?",index: 17),
    YesNoCard(question: "Did you ever have osteoporosis?",index: 18),
    YesNoCard(question: "Did you ever have colorectal polyps?",index: 19),
    YesNoCard(question: "Did you ever have a stroke?",index: 20),
    YesNoCard(question: "Have you ever Smoked?",index: 21),
    YesNoCard(question: "Do you smoke regularly now?",index: 22),
    YesNoCard(question: "How many years since you stopped smoking?",index: 23),
    YesNoCard(question: "How many packs did you smoke per day?",index: 24),
    YesNoCard(question: "During the last 12 months how many pills of aspirin or aspirin containing products do you usually take per day, per week, or per month?",index: 25),
    YesNoCard(question: "During the last 12 months have you regularly used Ibuprofen-containing products such as Advil, Nupril or Motrin?",index: 26),
    YesNoCard(question: "Is there a history of cancer in your family?",index: 27),
    YesNoCard(question: "Do you have a personal history of cancer?",index: 28),
    YesNoCard(question: "Has a doctor ever told you that you had an enlarged prostrate or benign prostatic hypertrophy?",index: 29),
    SliderCard(question: "How old were you when a doctor first told you you have an enlarged prostate or benign prostatic hypertrophy?",min: 30, max: 39, index: 30,changeFont: false,),
    YesNoCard(question: "Has a doctor ever told you that you had an inflamed prostate or prostatitis?",index: 31,),
    SliderCard(question: "How old were you when a doctor first told you you have an inflamed prostate or prostatitis?",min: 30, max: 39, index: 32, changeFont: false,),
    OtherAnswersCard(question: "In the past year, how many times did you wake up to urinate at night?", numberOfAnswers: 3, answerOne: "Never", answerTwo: "Once", answerThree: "Often",index: 33,),
    SliderCard(question: "How old were you when you first began waking up to urinate more than once a night on a regular basis?",min: 30, max: 39,index: 34,changeFont: false,),
    SliderCard(question: "How old were you when you first had a surgical procedure of the prostate?",min: 40, max: 49, index: 35,changeFont: false,),
    YesNoCard(question: "Did you ever have a biopsy of the prostrate?",index: 36,),
    YesNoCard(question: "Did you ever have a prostatectomy for benign disease?",index: 37,),
    YesNoCard(question: "Did you ever have a transurethral resection of prostate?",index: 38,),
    YesNoCard(question: "Have you had a vasectomy, that is, a sterilizaton procedure for men?",index: 39,),
    SliderCard(question: "How old were you when you had a vasectomy?", min: 20, max: 34, index: 40,changeFont: false,),
    SliderCard(question: "How old were you when you had your first menstrual period?", min: 0, max: 15, index: 41, changeFont: false,),
    YesNoCard(question: "Have you ever tried to become pregnant for a year or more without success?",index: 42, ),
    OtherAnswersCard(question: "Have you ever been pregnant?", numberOfAnswers: 3, answerOne: "Yes", answerTwo: "No",answerThree: "I don't know",index: 43,),
    OtherAnswersCard(question: "How many of your pregnancies resulted in a stilbirth?", numberOfAnswers: 3, answerOne: "0", answerTwo: "1",answerThree: "2+",index: 44,),
    OtherAnswersCard(question: "How many of your pregnancies resulted in a miscarriage or abortion?", numberOfAnswers: 3, answerOne: "0", answerTwo: "1",answerThree: "2+",index: 45,),
    OtherAnswersCard(question: "How many of your pregnancies resulted in one of your tubes, that is, a tubal or ectopic pregnancy?", numberOfAnswers: 3, answerOne: "0", answerTwo: "1",answerThree: "2+",index: 46,),
    SliderCard(question: "How many of your pregnancies resulted in a live birth?", min: 0, max: 10, index: 47,changeFont: false,),
    SliderCard(question: "How old were you when you had your first child?", min: 0, max: 100, index: 48,changeFont: false,),
    YesNoCard(question: "Did you ever take birth control pills for birth control or regular menstrual periods?",index: 49),
    SliderCard(question: "How old were you when you first started taking birth control pils?", min: 0, max: 50,index: 50,changeFont: false),
    OtherAnswersCard(question: "Have you ever had a tubal litigation, that is, have you had your tubes tied?", numberOfAnswers: 3, answerOne: "Yes", answerTwo: "No",answerThree: "I don't know",index: 51,),
    SliderCard(question: "How old were you when you first had your uterus removed?", min: 0, max: 100, index: 52,changeFont: false,),
    YesNoCard(question: "Have you ever removed your ovaries?",index: 53,),
    YesNoCard(question: "Have you ever used female hormones(tablets, pills, creams) for menopause?",index: 54,),
    YesNoCard(question: "Are you currently using female hormones?",index: 55,),
    OtherAnswersCard(question: "In total, how many years have you been using female hormones?", numberOfAnswers: 3, answerOne: "N/A", answerTwo: "Less than 10",answerThree: "10+",index: 56,),
    YesNoCard(question: "Have you ever had benign or fibrocystic breast disease?",index: 57,),
    YesNoCard(question: "Have you ever had benign ovarian tumor or cyst?",index: 58,),
    YesNoCard(question: "Have you ever had endemetriosis?",index: 59,),
    YesNoCard(question: "Have you ever had uterine fibroid tumors?",index: 60,),
  ];
}